Add change camera angle feat
Crop-Simulator/Python-API pull request #31
Opened 2023-07-07 09:52 UTC by taibohess

2023-07-07 11:04 UTC, wifimug approved these changes

2023-07-07 11:38 UTC, DanielSwarup requested changes

2023-07-07 11:38 UTC, DanielSwarup commented on src/controllers/camera_controller.py
> +    #                  camera_rotation=(1.57057,0.00174533,1.57057), collection_name="Collection"):
Ideally, do not commit commented-out code.

2023-07-07 11:38 UTC, DanielSwarup commented on tests/test_launch.py
> +    #     os.remove("tests/expected_output_seg.png")
Tear down needs to be uncommented

2023-07-07 11:42 UTC, DanielSwarup requested changes

2023-07-07 11:42 UTC, DanielSwarup commented on src/controllers/camera_controller.py
>          print("getting to render")
print statement should be removed

2023-07-07 15:04 UTC, DanielSwarup requested changes

2023-07-07 15:05 UTC, DanielSwarup commented
Small note: When you're done fixing the comments click the "Resolve Conversation" button so it's easier to navigate.

2023-07-10 16:19 UTC, DanielSwarup approved these changes
LGTM!

2023-07-10 17:32 UTC, taibohess commented
feat: add change camera angle

2023-07-10 17:33 UTC, taibohess commented
feat: add change camera angle

2023-07-10 17:33 UTC, closed without merging