feat: added textures to crops and lighting
Crop-Simulator/Python-API pull request #32
Opened 2023-07-07 14:27 UTC by wifimug

- added light controller
- added crop textures
- added sky background

2023-07-07 15:06 UTC, DanielSwarup commented
For future note, the two features should have been two separate PRs

2023-07-07 15:08 UTC, wifimug commented
> For future note, the two features should have been two separate PRs

Yes, initially it was only meant to be texture but I couldn't see it applied without the lighting. Should I split it anyways?

2023-07-07 15:09 UTC, DanielSwarup requested changes
Minor changes with commented-out code. Looking forward to Unit tests.

In the future, let's have one feat + its unit test in a single PR.

2023-07-07 15:09 UTC, DanielSwarup commented on src/controllers/crop_controller.py
> +            # crop_model.active_material = material
If not important, remove commented out code

2023-07-07 15:09 UTC, DanielSwarup commented on src/controllers/crop_controller.py
> +            # material.diffuse_color = (1,0,0,0.8)
Same here

2023-07-07 15:09 UTC, DanielSwarup commented on src/controllers/crop_controller.py
> +            # material.diffuse_color = (0,1,0,0.8)
And here

2023-07-07 15:09 UTC, DanielSwarup commented on src/controllers/crop_controller.py
> +            # material.diffuse_color = (0,0,1,0.8)
And here

2023-07-07 15:09 UTC, DanielSwarup commented on src/launch.py
> +        # dupe.hide_set(True)
Same here

2023-07-10 21:08 UTC, wifimug commented
Accidentally reset my commit and then committed a merge conflict merge. That's why there's two there.

2023-07-10 21:59 UTC, DanielSwarup commented
> Accidentally reset my commit and then committed a merge conflict merge. That's why there's two there.

Would recommend performing a squash merge when merging

2023-07-11 00:25 UTC, closed without merging