feat: generated colored segmentation according to ControlNet protocol
Crop-Simulator/Python-API pull request #40
Opened 2023-07-17 11:35 UTC by SeanChao

2023-07-17 13:45 UTC, wifimug approved these changes
Exciting developments!

2023-07-18 10:12 UTC, DanielSwarup requested changes

2023-07-18 10:12 UTC, DanielSwarup commented on src/controllers/segmentation.py
> +class SegmentationClass:
It would be better to use Enum type here https://docs.python.org/3/library/enum.html

2023-07-18 10:12 UTC, DanielSwarup commented on src/controllers/segmentation.py
>                          "WARNING: Unknown segmentation id: "
Would be better to raise a warning here instead of printing https://docs.python.org/3/library/warnings.html#warnings.warn

2023-07-18 14:48 UTC, DanielSwarup approved these changes
LGTM!

2023-07-18 22:11 UTC, merged