feat: add multiple crop stages
Crop-Simulator/Python-API pull request #42
Opened 2023-07-17 17:46 UTC by wifimug

- Add multiple crop stages in one scene
- Unit tests for crop stages

2023-07-17 18:57 UTC, donghangdu reviewed
Unitest failed

2023-07-18 13:05 UTC, DanielSwarup requested changes

2023-07-18 13:05 UTC, DanielSwarup commented on tests/controllers/test_crop_controller.py
> +                if "stage10" in obj.name:
A use dictionary instead of hard coding it like this. A two sum like solution!

2023-07-18 13:05 UTC, DanielSwarup commented on tests/controllers/test_crop_controller.py
> +        material, segmentation_id = crop_controller.assign_crop_type("stage1")
It would be best to assign materials to all of the stages and check them all in a loop.

2023-07-18 13:05 UTC, DanielSwarup commented on src/renderers/scene_renderer.py
> +        cameracon.setup_camera("camera_one", (10,0,0), (1.57057,0.00174533,1.57057), "Collection")
"Collection" should not be a hard-coded string. Instead it should be the `collection` variable which is already being passed during initialisation

2023-07-18 13:05 UTC, DanielSwarup commented on src/launch.py
> +        collection1 = bpy.data.collections.get("Collection")
Similar comment to the one below. "Collection" should not be a hard-coded string instead, it should be the variable `collection`

2023-07-18 13:05 UTC, DanielSwarup commented on src/launch.py
> +        # bpy.ops.object.delete()
Remove commented code if its not in use

2023-07-19 17:46 UTC, DanielSwarup approved these changes
A long PR but the changes look good!

2023-07-19 18:06 UTC, SeanChao approved these changes
Great work!

2023-07-20 01:59 UTC, merged