feat: add nutrient controller
Crop-Simulator/Python-API pull request #44
Opened 2023-07-18 12:10 UTC by taibohess

2023-07-18 17:15 UTC, DanielSwarup requested changes
Unit Tests would be preferred.

2023-07-18 17:15 UTC, DanielSwarup commented on src/launch.py
> +        wc = WeatherController("2b8fb3c4f62844189b7edec1063d92f9")
Is this a secret key? If yes this should immediately be changed/revoked and GitHub secrets should be used instead.

2023-07-26 13:48 UTC, wifimug approved these changes

2023-07-27 11:14 UTC, DanielSwarup commented
API key is still in the code

2023-08-15 05:16 UTC, closed without merging