feat: edit render resolution through data file
Crop-Simulator/Python-API pull request #51
Opened 2023-07-24 17:24 UTC by wifimug

2023-07-24 17:54 UTC, DanielSwarup requested changes

2023-07-24 17:54 UTC, DanielSwarup commented on src/launch.py
> +        scenerender = SceneRenderer(config["outfile"][0], collection, config["resolution"])
I think it may be better to just pass `config` as one attribute and then access it later

2023-07-24 17:54 UTC, DanielSwarup commented on tests/test_data.yml
> +  percentage_share:
Isn't this file auto-generated via the tests? This shouldn't be pushed if it is.

2023-07-26 10:08 UTC, DanielSwarup approved these changes
LGTM!

2023-07-26 10:08 UTC, DanielSwarup commented
Would recommend "Squash Merge"

2023-07-26 14:19 UTC, taibohess approved these changes

2023-07-26 14:33 UTC, merged