Cropsim 170 semantic segmentation annotation
Crop-Simulator/Python-API pull request #91
Opened 2023-09-03 01:54 UTC by Hyridex

2023-09-03 02:24 UTC, wifimug approved these changes

2023-09-03 17:55 UTC, DanielSwarup requested changes

2023-09-03 17:55 UTC, DanielSwarup commented on src/machine_learning/utilities/interactive_annotator.py
> +config = {}
Could some unit tests and documentation READMEs be added to this?

2023-09-03 17:55 UTC, DanielSwarup commented on src/machine_learning/utilities/data_preprocess.py
> +def extract_frames(video_path: str, output_dir: str, frame_interval: int = 1,
unit tests would be nice

2023-09-03 20:58 UTC, SeanChao approved these changes

2023-09-04 11:13 UTC, DanielSwarup approved these changes
LGTM!

2023-09-04 13:04 UTC, merged